[project]
name = "1brc"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sid Mitra <sidmitra.del@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
