[project]
name = "1brc"
version = "0.1.0"
description = "One Billion Row Challege (with Python)"
authors = ["Sid Mitra <github@sidmitra.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
pip = ">=23.3.2,<23.4"
scalene = ">=1.5.31.1,<1.5.32"
